[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip --quiet",
  "pip install --no-cache-dir -r requirements.txt --quiet"
]

[start]
cmd = "python userbot.py"
